apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins_test-app
spec:
  selector:
    matchLabels:
      app: jenkins_test-app
  template:
    metadata:
      labels:
        app: jenkins_test-app
    spec:
      containers:
        - name: jenkins_test-app
          image: IMAGE_URL/jenkins_test
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins_test-svc
spec:
  type: LoadBalancer
  selector:
    app: jenkins_test-app
  ports:
    - port: 80
      targetPort: 9090