apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test-app
spec:
  replicas: 1  # Scale to 3 replicas
  selector:
    matchLabels:
      app: jenkins-test-app
  template:
    metadata:
      labels:
        app: jenkins-test-app
    spec:
      containers:
        - name: jenkins-test-app
          image: IMAGE_URL/jenkins_test
          resources:
            requests:
              cpu: 100m
              memory: 2Gi  # 1 gigabyte of memory
            limits:
              cpu: 500m
              memory: 3Gi  # 1 gigabyte of memory
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-svc
spec:
  type: LoadBalancer
  selector:
    app: jenkins-test-app
  ports:
    - port: 80
      targetPort: 9090
